import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import {CalendarDays, Eye, Gauge, LogOut, Medal, Shield, SlidersHorizontal, Trophy, Users, ClipboardList, Flag, Plus, Save, Trash2, Edit3} from 'lucide-react';
import './style.css';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseKey = import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase = createClient(supabaseUrl || '', supabaseKey || '');

function flagUrl(code){ return code ? `https://flagcdn.com/w40/${code}.png` : ''; }
function fmtDate(d){ if(!d) return 'Sem data'; return new Date(d).toLocaleString('pt-BR',{dateStyle:'short', timeStyle:'short'}); }
function calcPoints(j,p){
  if(!j || !p || j.gols_a===null || j.gols_b===null || j.gols_a===undefined || j.gols_b===undefined) return null;
  const RA=Number(j.gols_a), RB=Number(j.gols_b), PA=Number(p.gols_a), PB=Number(p.gols_b);
  if(PA===RA && PB===RB) return 5;
  if(RA===RB) return PA===PB ? 3 : 0;
  if(PA===PB) return 0;
  if((RA>RB && PA===RA) || (RB>RA && PB===RB)) return 3;
  if((RA>RB && PB===RB) || (RB>RA && PA===RA)) return 2;
  if((RA>RB && PA>PB) || (RB>RA && PB>PA)) return 1;
  return 0;
}

function App(){
  const [session,setSession]=useState(null); const [profile,setProfile]=useState(null); const [loading,setLoading]=useState(true); const [msg,setMsg]=useState('');
  useEffect(()=>{ supabase.auth.getSession().then(({data})=>{ setSession(data.session); setLoading(false);}); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return ()=>subscription.unsubscribe(); },[]);
  useEffect(()=>{ if(session?.user) loadProfile(); else setProfile(null); },[session]);
  async function loadProfile(){
    let {data,error}=await supabase.from('participantes').select('*').eq('id',session.user.id).maybeSingle();
    if(!data && !error){ await supabase.from('participantes').insert({id:session.user.id,email:session.user.email,nome:session.user.email?.split('@')[0]}); ({data}=await supabase.from('participantes').select('*').eq('id',session.user.id).maybeSingle()); }
    setProfile(data);
  }
  if(loading) return <div className="center">Carregando...</div>;
  if(!session) return <Auth />;
  return <Shell profile={profile} session={session} setMsg={setMsg} msg={msg} refreshProfile={loadProfile}/>;
}

function Auth(){
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [nome,setNome]=useState(''); const [mode,setMode]=useState('login'); const [msg,setMsg]=useState('');
  async function submit(){ setMsg('');
    const res = mode==='login' ? await supabase.auth.signInWithPassword({email,password}) : await supabase.auth.signUp({email,password,options:{data:{nome}}});
    if(res.error) setMsg(res.error.message); else setMsg(mode==='login'?'Autenticado.':'Cadastro criado. Verifique o email se a confirmação estiver ativa.');
  }
  async function reset(){ if(!email) return setMsg('Informe seu email.'); const {error}=await supabase.auth.resetPasswordForEmail(email); setMsg(error?error.message:'Email de recuperação enviado.'); }
  return <div className="auth"><div className="authCard"><h1>Bolão Copa Cartola</h1><p>Sistema de palpites da fase de grupos</p>{mode==='signup'&&<input placeholder="Nome" value={nome} onChange={e=>setNome(e.target.value)}/>}<input placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="Senha" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><button onClick={submit}>{mode==='login'?'Entrar':'Criar conta'}</button><button className="ghost" onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'Criar conta':'Já tenho conta'}</button><button className="link" onClick={reset}>Esqueci minha senha</button>{msg&&<div className="notice">{msg}</div>}</div></div>
}

const menuBase=[['dashboard','Dashboard',Gauge],['meus','Meus Palpites',ClipboardList],['ver','Ver Palpites',Eye],['calendario','Calendário de Jogos',CalendarDays],['ranking','Ranking',Medal]];
const menuAdmin=[['admin-config','Configuração',SlidersHorizontal],['admin-selecoes','Seleções',Flag],['admin-grupos','Grupos',Shield],['admin-jogos','Jogos',Trophy],['admin-resultados','Resultados',Save],['admin-participantes','Participantes',Users]];
function Shell({profile,session,msg,setMsg,refreshProfile}){ const [page,setPage]=useState('dashboard'); const admin=profile?.perfil==='admin';
  return <div className="app"><aside><div className="brand">🏆 Bolão Copa</div><div className="user">{profile?.nome||session.user.email}<br/><small>{profile?.perfil||'participante'}</small></div><nav>{menuBase.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><Icon size={18}/>{label}</button>)}{admin&&<><hr/>{menuAdmin.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><Icon size={18}/>{label}</button>)}</>}<button onClick={()=>supabase.auth.signOut()}><LogOut size={18}/>Sair</button></nav></aside><main>{msg&&<div className="toast" onClick={()=>setMsg('')}>{msg}</div>}<Page page={page} profile={profile} setMsg={setMsg} refreshProfile={refreshProfile}/></main></div>
}
function Page({page,profile,setMsg,refreshProfile}){ const props={profile,setMsg,refreshProfile}; return {dashboard:<Dashboard/>,meus:<MeusPalpites {...props}/>,ver:<VerPalpites/>,calendario:<Calendario/>,ranking:<Ranking/>, 'admin-config':<AdminConfig setMsg={setMsg}/>, 'admin-selecoes':<AdminSelecoes setMsg={setMsg}/>, 'admin-grupos':<AdminGrupos setMsg={setMsg}/>, 'admin-jogos':<AdminJogos setMsg={setMsg}/>, 'admin-resultados':<AdminResultados setMsg={setMsg}/>, 'admin-participantes':<AdminParticipantes setMsg={setMsg} refreshProfile={refreshProfile}/>}[page]||<Dashboard/>; }

function useData(){ const [data,setData]=useState({jogos:[],selecoes:[],palpites:[],participantes:[],config:null,grupos:[]}); const [loading,setLoading]=useState(true);
  async function load(){ setLoading(true); const [jogos,selecoes,palpites,participantes,config,grupos]=await Promise.all([
    supabase.from('jogos').select('*,a:selecao_a_id(id,nome,codigo_bandeira),b:selecao_b_id(id,nome,codigo_bandeira)').order('data_hora',{ascending:true}),
    supabase.from('selecoes').select('*').order('grupo').order('nome'), supabase.from('palpites').select('*'), supabase.from('participantes').select('*').order('nome'), supabase.from('configuracao_bolao').select('*').eq('id',1).maybeSingle(), supabase.from('grupos').select('*').order('ordem')]);
    setData({jogos:jogos.data||[],selecoes:selecoes.data||[],palpites:palpites.data||[],participantes:participantes.data||[],config:config.data,grupos:grupos.data||[]}); setLoading(false);
  }
  useEffect(()=>{load()},[]); return {...data,loading,load};
}
function Dashboard(){ const {jogos,palpites,participantes,loading}=useData(); if(loading)return <h2>Carregando...</h2>; const finalizados=jogos.filter(j=>j.gols_a!==null&&j.gols_b!==null).length; return <><h1>Dashboard</h1><div className="grid4"><KPI t="Participantes" v={participantes.length}/><KPI t="Jogos" v={jogos.length}/><KPI t="Jogos finalizados" v={finalizados}/><KPI t="Palpites salvos" v={palpites.length}/></div></> }
function KPI({t,v}){return <div className="kpi"><span>{t}</span><b>{v}</b></div>}
function GameCard({j,children}){return <div className="game"><div className="team"><img src={flagUrl(j.a?.codigo_bandeira)}/><span>{j.a?.nome||'Time A'}</span></div><div className="mid">{children}</div><div className="team right"><span>{j.b?.nome||'Time B'}</span><img src={flagUrl(j.b?.codigo_bandeira)}/></div><div className="meta">Grupo {j.grupo||'-'} • Rodada {j.rodada||'-'} • {fmtDate(j.data_hora)}</div></div>}

function MeusPalpites({profile,setMsg}){ const {jogos,palpites,config,loading,load}=useData(); const [vals,setVals]=useState({}); useEffect(()=>{ const obj={}; palpites.filter(p=>p.participante_id===profile?.id).forEach(p=>obj[p.jogo_id]={a:p.gols_a,b:p.gols_b}); setVals(obj);},[palpites,profile]); if(loading)return <h2>Carregando...</h2>; const blocked=config?.limite_palpite && new Date()>new Date(config.limite_palpite);
  async function save(){ const rows=Object.entries(vals).filter(([,v])=>v.a!==''&&v.b!==''&&v.a!==undefined&&v.b!==undefined).map(([jogo_id,v])=>({participante_id:profile.id,jogo_id:Number(jogo_id),gols_a:Number(v.a),gols_b:Number(v.b),updated_at:new Date().toISOString()})); if(!rows.length)return setMsg('Nenhum palpite preenchido.'); const {error}=await supabase.from('palpites').upsert(rows,{onConflict:'participante_id,jogo_id'}); setMsg(error?error.message:'Palpites salvos com sucesso.'); if(!error) load(); }
  return <><h1>Meus Palpites</h1>{blocked&&<div className="warn">Prazo encerrado. Palpites bloqueados.</div>}<div className="cards">{jogos.map(j=>{const v=vals[j.id]||{}; const p=palpites.find(x=>x.participante_id===profile.id&&x.jogo_id===j.id); const pts=calcPoints(j,p); return <GameCard key={j.id} j={j}><input disabled={blocked} type="number" min="0" value={v.a??''} onChange={e=>setVals({...vals,[j.id]:{...v,a:e.target.value}})}/><b>x</b><input disabled={blocked} type="number" min="0" value={v.b??''} onChange={e=>setVals({...vals,[j.id]:{...v,b:e.target.value}})}/><small>Oficial: {j.gols_a===null||j.gols_b===null?'aguardando':`${j.gols_a} x ${j.gols_b}`}</small><small>Pontos: {pts===null?'aguardando':pts}</small></GameCard>})}</div><button className="floating" onClick={save}><Save size={18}/> Salvar Palpites</button></> }

function VerPalpites(){ const {jogos,palpites,participantes,loading}=useData(); const [uid,setUid]=useState(''); useEffect(()=>{ if(!uid && participantes[0]) setUid(participantes[0].id);},[participantes]); if(loading)return <h2>Carregando...</h2>; return <><h1>Ver Palpites</h1><select className="selectTop" value={uid} onChange={e=>setUid(e.target.value)}>{participantes.map(p=><option key={p.id} value={p.id}>{p.nome||p.email}</option>)}</select><div className="cards">{jogos.map(j=>{const p=palpites.find(x=>x.participante_id===uid&&x.jogo_id===j.id); const pts=calcPoints(j,p); return <GameCard key={j.id} j={j}><div className="readonlyScore">{p?`${p.gols_a} x ${p.gols_b}`:'Sem palpite'}</div><small>Oficial: {j.gols_a===null||j.gols_b===null?'aguardando':`${j.gols_a} x ${j.gols_b}`}</small><small>Pontos: {pts===null?'aguardando':pts}</small></GameCard>})}</div></> }
function Calendario(){ const {jogos,loading}=useData(); if(loading)return <h2>Carregando...</h2>; return <><h1>Calendário de Jogos</h1><div className="cards">{jogos.map(j=><GameCard key={j.id} j={j}><div className="readonlyScore">{j.gols_a===null||j.gols_b===null?'x':`${j.gols_a} x ${j.gols_b}`}</div><small>Status: {j.status||'aberto'}</small></GameCard>)}</div></> }
function Ranking(){ const {jogos,palpites,participantes,loading}=useData(); if(loading)return <h2>Carregando...</h2>; const rows=participantes.map(u=>{ const ps=palpites.filter(p=>p.participante_id===u.id); let total=0,exatos=0; ps.forEach(p=>{ const j=jogos.find(x=>x.id===p.jogo_id); const pts=calcPoints(j,p); if(pts!==null) total+=pts; if(pts===5) exatos++;}); return {...u,total,exatos,feitos:ps.length};}).sort((a,b)=>b.total-a.total||b.exatos-a.exatos); return <><h1>Ranking</h1><table><thead><tr><th>#</th><th>Participante</th><th>Pontos</th><th>Placar exato</th><th>Palpites</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.id}><td>{i+1}</td><td>{r.nome||r.email}</td><td>{r.total}</td><td>{r.exatos}</td><td>{r.feitos}</td></tr>)}</tbody></table></> }

function AdminConfig({setMsg}){ const {config,loading,load}=useData(); const [c,setC]=useState(null); useEffect(()=>setC(config),[config]); if(loading||!c)return <h2>Carregando...</h2>; async function save(){ const {error}=await supabase.from('configuracao_bolao').update(c).eq('id',1); setMsg(error?error.message:'Configuração salva.'); if(!error)load(); } async function gerarGrupos(){ const n=Number(c.total_grupos||12); const rows=Array.from({length:n},(_,i)=>({nome:String.fromCharCode(65+i),ordem:i+1})); const {error}=await supabase.from('grupos').upsert(rows,{onConflict:'nome'}); setMsg(error?error.message:'Grupos gerados.'); if(!error)load(); }
 return <><h1>Configuração do Bolão</h1><div className="form"><label>Nome<input value={c.nome||''} onChange={e=>setC({...c,nome:e.target.value})}/></label><label>Total de seleções<input type="number" value={c.total_selecoes||48} onChange={e=>setC({...c,total_selecoes:Number(e.target.value)})}/></label><label>Total de grupos<input type="number" value={c.total_grupos||12} onChange={e=>setC({...c,total_grupos:Number(e.target.value)})}/></label><label>Seleções por grupo<input type="number" value={c.selecoes_por_grupo||4} onChange={e=>setC({...c,selecoes_por_grupo:Number(e.target.value)})}/></label><label>Limite palpites<input type="datetime-local" value={c.limite_palpite?.slice(0,16)||''} onChange={e=>setC({...c,limite_palpite:e.target.value})}/></label><button onClick={save}><Save size={18}/>Salvar</button><button onClick={gerarGrupos}><Plus size={18}/>Gerar grupos</button></div></> }
function AdminSelecoes({setMsg}){ const {selecoes,grupos,loading,load}=useData(); const [f,setF]=useState({nome:'',codigo_bandeira:'',grupo:'A'}); if(loading)return <h2>Carregando...</h2>; async function save(){ const {error}=await supabase.from('selecoes').insert(f); setMsg(error?error.message:'Seleção cadastrada.'); if(!error){setF({nome:'',codigo_bandeira:'',grupo:'A'});load();}} async function del(id){ if(!confirm('Excluir seleção?'))return; const {error}=await supabase.from('selecoes').delete().eq('id',id); setMsg(error?error.message:'Seleção excluída.'); if(!error)load();}
 return <><h1>Seleções</h1><div className="inline"><input placeholder="Nome" value={f.nome} onChange={e=>setF({...f,nome:e.target.value})}/><input placeholder="Código bandeira ex: br" value={f.codigo_bandeira} onChange={e=>setF({...f,codigo_bandeira:e.target.value})}/><select value={f.grupo} onChange={e=>setF({...f,grupo:e.target.value})}>{grupos.map(g=><option key={g.nome}>{g.nome}</option>)}</select><button onClick={save}><Plus size={18}/>Adicionar</button></div><div className="list">{selecoes.map(s=><div className="row" key={s.id}><span><img src={flagUrl(s.codigo_bandeira)}/> {s.nome}</span><b>Grupo {s.grupo}</b><button onClick={()=>del(s.id)}><Trash2 size={16}/></button></div>)}</div></> }
function AdminGrupos(){ const {grupos,selecoes,loading}=useData(); if(loading)return <h2>Carregando...</h2>; return <><h1>Grupos</h1><div className="groupGrid">{grupos.map(g=><div className="group" key={g.id}><h2>Grupo {g.nome}</h2>{selecoes.filter(s=>s.grupo===g.nome).map(s=><p key={s.id}><img src={flagUrl(s.codigo_bandeira)}/> {s.nome}</p>)}</div>)}</div></> }
function AdminJogos({setMsg}){ const {jogos,selecoes,grupos,loading,load}=useData(); const [f,setF]=useState({grupo:'A',rodada:1,selecao_a_id:'',selecao_b_id:'',data_hora:''}); if(loading)return <h2>Carregando...</h2>; const selGrupo=selecoes.filter(s=>s.grupo===f.grupo);
 async function save(){ const row={...f,selecao_a_id:Number(f.selecao_a_id),selecao_b_id:Number(f.selecao_b_id),rodada:Number(f.rodada),data_hora:f.data_hora||null}; const {error}=await supabase.from('jogos').insert(row); setMsg(error?error.message:'Jogo criado.'); if(!error)load(); }
 async function gerarGrupo(g){ const ss=selecoes.filter(s=>s.grupo===g); const rows=[]; for(let i=0;i<ss.length;i++)for(let j=i+1;j<ss.length;j++)rows.push({grupo:g,rodada:1,selecao_a_id:ss[i].id,selecao_b_id:ss[j].id,status:'aberto'}); const {error}=await supabase.from('jogos').insert(rows); setMsg(error?error.message:`${rows.length} jogos gerados no grupo ${g}.`); if(!error)load(); }
 async function gerarTodos(){ for(const g of grupos) await gerarGrupo(g.nome); }
 async function del(id){ if(!confirm('Excluir jogo?'))return; const {error}=await supabase.from('jogos').delete().eq('id',id); setMsg(error?error.message:'Jogo excluído.'); if(!error)load(); }
 return <><h1>Jogos</h1><div className="inline"><select value={f.grupo} onChange={e=>setF({...f,grupo:e.target.value,selecao_a_id:'',selecao_b_id:''})}>{grupos.map(g=><option key={g.nome}>{g.nome}</option>)}</select><input type="number" value={f.rodada} onChange={e=>setF({...f,rodada:e.target.value})}/><select value={f.selecao_a_id} onChange={e=>setF({...f,selecao_a_id:e.target.value})}><option>Time A</option>{selGrupo.map(s=><option key={s.id} value={s.id}>{s.nome}</option>)}</select><select value={f.selecao_b_id} onChange={e=>setF({...f,selecao_b_id:e.target.value})}><option>Time B</option>{selGrupo.map(s=><option key={s.id} value={s.id}>{s.nome}</option>)}</select><input type="datetime-local" value={f.data_hora} onChange={e=>setF({...f,data_hora:e.target.value})}/><button onClick={save}>Criar</button></div><div className="inline">{grupos.map(g=><button key={g.nome} onClick={()=>gerarGrupo(g.nome)}>Gerar grupo {g.nome}</button>)}<button onClick={gerarTodos}>Gerar todos</button></div><table><thead><tr><th>Grupo</th><th>Jogo</th><th>Data</th><th></th></tr></thead><tbody>{jogos.map(j=><tr key={j.id}><td>{j.grupo}</td><td>{j.a?.nome} x {j.b?.nome}</td><td>{fmtDate(j.data_hora)}</td><td><button onClick={()=>del(j.id)}><Trash2 size={16}/></button></td></tr>)}</tbody></table></> }
function AdminResultados({setMsg}){ const {jogos,loading,load}=useData(); const [vals,setVals]=useState({}); if(loading)return <h2>Carregando...</h2>; async function save(j){ const v=vals[j.id]||{}; const {error}=await supabase.from('jogos').update({gols_a:v.a===''?null:Number(v.a??j.gols_a),gols_b:v.b===''?null:Number(v.b??j.gols_b),status:'finalizado'}).eq('id',j.id); setMsg(error?error.message:'Resultado salvo.'); if(!error)load(); }
 return <><h1>Resultados Oficiais</h1>{jogos.map(j=>{const v=vals[j.id]||{};return <GameCard key={j.id} j={j}><input type="number" min="0" value={v.a??j.gols_a??''} onChange={e=>setVals({...vals,[j.id]:{...v,a:e.target.value}})}/><b>x</b><input type="number" min="0" value={v.b??j.gols_b??''} onChange={e=>setVals({...vals,[j.id]:{...v,b:e.target.value}})}/><button onClick={()=>save(j)}>Salvar</button></GameCard>})}</> }
function AdminParticipantes({setMsg,refreshProfile}){ const {participantes,loading,load}=useData(); if(loading)return <h2>Carregando...</h2>; async function setPerfil(p,perfil){ const {error}=await supabase.from('participantes').update({perfil}).eq('id',p.id); setMsg(error?error.message:'Perfil atualizado.'); if(!error){load(); refreshProfile?.();} }
 return <><h1>Participantes</h1><table><thead><tr><th>Nome</th><th>Email</th><th>Perfil</th><th>Ação</th></tr></thead><tbody>{participantes.map(p=><tr key={p.id}><td>{p.nome}</td><td>{p.email}</td><td>{p.perfil}</td><td><button onClick={()=>setPerfil(p,p.perfil==='admin'?'participante':'admin')}>{p.perfil==='admin'?'Tornar participante':'Tornar admin'}</button></td></tr>)}</tbody></table></> }

createRoot(document.getElementById('root')).render(<App/>);
