import React, {useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {supabase} from './supabase';
import {Lock, Trophy, Save, Users, Eye, Settings, Plus, LogOut} from 'lucide-react';
import './style.css';

const flag=(code)=> code ? `https://flagcdn.com/w40/${code.toLowerCase()}.png` : '';
const score = (ra,rb,pa,pb)=>{
  if([ra,rb,pa,pb].some(v=>v===null||v===undefined||v==='')) return null;
  ra=+ra; rb=+rb; pa=+pa; pb=+pb;
  if(pa===ra && pb===rb) return 5;
  if(ra===rb) return pa===pb ? 3 : 0;
  if(pa===pb) return 0;
  if((ra>rb && pa===ra) || (rb>ra && pb===rb)) return 3;
  if((ra>rb && pb===rb) || (rb>ra && pa===ra)) return 2;
  if((ra>rb && pa>pb) || (rb>ra && pb>pa)) return 1;
  return 0;
};

function App(){
 const [session,setSession]=useState(null),[page,setPage]=useState('palpites'),[profile,setProfile]=useState(null),[loading,setLoading]=useState(true);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)}); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{ if(session) loadProfile(); else setProfile(null)},[session]);
 async function loadProfile(){ const {data}=await supabase.from('participantes').select('*').eq('id',session.user.id).single(); setProfile(data); }
 if(loading) return <div className="center">Carregando...</div>;
 if(!session) return <Auth/>;
 return <Shell page={page} setPage={setPage} profile={profile} onLogout={()=>supabase.auth.signOut()}><Main page={page} profile={profile}/></Shell>
}
function Auth(){
 const [mode,setMode]=useState('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[nome,setNome]=useState(''),[msg,setMsg]=useState('');
 async function submit(e){e.preventDefault(); setMsg('');
  if(mode==='login'){ const {error}=await supabase.auth.signInWithPassword({email,password}); if(error)setMsg(error.message); }
  if(mode==='signup'){ const {data,error}=await supabase.auth.signUp({email,password,options:{data:{nome}}}); if(error)setMsg(error.message); else setMsg('Cadastro criado. Confira seu e-mail, se a confirmação estiver ativa.'); }
  if(mode==='reset'){ const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin}); setMsg(error?error.message:'Enviamos o link de recuperação para seu e-mail.'); }
 }
 return <div className="auth"><form onSubmit={submit} className="authbox"><h1>Bolão da Copa</h1><p>Sistema de palpites estilo Cartola</p>{mode==='signup'&&<input placeholder="Nome" value={nome} onChange={e=>setNome(e.target.value)} required/>}<input placeholder="E-mail" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/>{mode!=='reset'&&<input placeholder="Senha" type="password" value={password} onChange={e=>setPassword(e.target.value)} required/>}<button>{mode==='login'?'Entrar':mode==='signup'?'Criar login':'Recuperar senha'}</button><div className="links"><a onClick={()=>setMode('login')}>Entrar</a><a onClick={()=>setMode('signup')}>Criar login</a><a onClick={()=>setMode('reset')}>Esqueci a senha</a></div>{msg&&<small>{msg}</small>}</form></div>
}
function Shell({children,page,setPage,profile,onLogout}){ const isAdmin=profile?.perfil==='admin'; const items=[['palpites','Palpites'],['ranking','Ranking'],['ver','Ver palpites'], ...(isAdmin?[['admin','Admin']]:[])]; return <><header><b>🏆 Bolão da Copa</b><nav>{items.map(i=><button className={page===i[0]?'sel':''} onClick={()=>setPage(i[0])} key={i[0]}>{i[1]}</button>)}<button onClick={onLogout}><LogOut size={16}/> Sair</button></nav></header><main>{children}</main></> }
function Main({page,profile}){ if(page==='ranking')return <Ranking/>; if(page==='ver')return <VerPalpites/>; if(page==='admin')return <Admin profile={profile}/>; return <Palpites profile={profile}/> }
function useData(){ const [cfg,setCfg]=useState(null),[jogos,setJogos]=useState([]),[palpites,setPalpites]=useState([]); async function load(){ const {data:c}=await supabase.from('configuracao_bolao').select('*').limit(1).single(); setCfg(c); const {data:j}=await supabase.from('jogos').select('*, time_a:selecoes!jogos_time_a_id_fkey(*), time_b:selecoes!jogos_time_b_id_fkey(*)').order('data_hora'); setJogos(j||[]); const {data:p}=await supabase.from('palpites').select('*'); setPalpites(p||[]);} useEffect(()=>{load()},[]); return {cfg,jogos,palpites,load}; }
function Palpites({profile}){ const {cfg,jogos,palpites,load}=useData(); const [draft,setDraft]=useState({}),[msg,setMsg]=useState(''); const bloqueado=cfg?.limite_palpite && new Date()>new Date(cfg.limite_palpite);
 useEffect(()=>{ const mine=palpites.filter(p=>p.participante_id===profile?.id); const d={}; mine.forEach(p=>{d[p.jogo_id]={a:p.gols_a,b:p.gols_b}}); setDraft(d)},[palpites,profile]);
 async function salvar(){ if(bloqueado){setMsg('Prazo encerrado. Palpites bloqueados.'); return;} const rows=Object.entries(draft).filter(([_,v])=>v.a!==''&&v.b!==''&&v.a!=null&&v.b!=null).map(([j,v])=>({participante_id:profile.id,jogo_id:+j,gols_a:+v.a,gols_b:+v.b})); const {error}=await supabase.from('palpites').upsert(rows,{onConflict:'participante_id,jogo_id'}); setMsg(error?error.message:'Palpites salvos com sucesso.'); load(); }
 const byDate=jogos.reduce((acc,j)=>{const d=new Date(j.data_hora).toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'short'}); (acc[d]??=[]).push(j); return acc},{});
 return <section><h2>Meus palpites {bloqueado&&<span className="badge"><Lock size={14}/> encerrado</span>}</h2>{Object.entries(byDate).map(([d,lista])=><div key={d}><h3>{d}</h3><div className="grid">{lista.map(j=><GameCard key={j.id} j={j} val={draft[j.id]||{a:'',b:''}} disabled={bloqueado} onChange={(side,val)=>setDraft({...draft,[j.id]:{...(draft[j.id]||{}),[side]:val}})}/>)}</div></div>)}<button className="save" onClick={salvar}><Save size={18}/> Salvar palpites</button>{msg&&<p>{msg}</p>}</section> }
function GameCard({j,val,onChange,disabled}){return <div className="card"><div className="meta"><span>{j.grupo_nome||j.grupo}</span><b>{new Date(j.data_hora).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</b></div><div className="match"><div className="team"><img src={flag(j.time_a?.codigo_bandeira)} /> <span>{j.time_a?.nome}</span></div><input disabled={disabled} type="number" min="0" value={val.a??''} onChange={e=>onChange('a',e.target.value)}/><b>x</b><input disabled={disabled} type="number" min="0" value={val.b??''} onChange={e=>onChange('b',e.target.value)}/><div className="team right"><span>{j.time_b?.nome}</span><img src={flag(j.time_b?.codigo_bandeira)} /></div></div></div>}
function Ranking(){ const {jogos,palpites}=useData(); const [parts,setParts]=useState([]); useEffect(()=>{supabase.from('participantes').select('*').then(({data})=>setParts(data||[]))},[]); const rows=parts.map(u=>{let total=0,exatos=0; palpites.filter(p=>p.participante_id===u.id).forEach(p=>{const j=jogos.find(x=>x.id===p.jogo_id); const pts=score(j?.gols_a,j?.gols_b,p.gols_a,p.gols_b); if(pts!=null){total+=pts; if(pts===5)exatos++;}}); return {...u,total,exatos}}).sort((a,b)=>b.total-a.total||b.exatos-a.exatos); return <section><h2><Trophy/> Ranking</h2><table><thead><tr><th>#</th><th>Participante</th><th>Pontos</th><th>Placares exatos</th></tr></thead><tbody>{rows.map((r,i)=><tr><td>{i+1}</td><td>{r.nome}</td><td>{r.total}</td><td>{r.exatos}</td></tr>)}</tbody></table></section> }
function VerPalpites(){ const {jogos,palpites}=useData(); const [parts,setParts]=useState([]); useEffect(()=>{supabase.from('participantes').select('*').then(({data})=>setParts(data||[]))},[]); return <section><h2><Eye/> Palpites de todos</h2><table><thead><tr><th>Jogo</th>{parts.map(p=><th>{p.nome}</th>)}</tr></thead><tbody>{jogos.map(j=><tr><td>{j.time_a?.nome} x {j.time_b?.nome}</td>{parts.map(p=>{const pal=palpites.find(x=>x.jogo_id===j.id&&x.participante_id===p.id); return <td>{pal?`${pal.gols_a} x ${pal.gols_b}`:'-'}</td>})}</tr>)}</tbody></table></section> }
function Admin(){ return <section><h2><Settings/> Administração</h2><AdminConfig/><AdminSelecoes/><AdminJogos/></section> }
function AdminConfig(){ const [cfg,setCfg]=useState({nome:'Copa 2026',qtd_selecoes:48,qtd_grupos:12,limite_palpite:'2026-06-01T23:59:59'}); useEffect(()=>{supabase.from('configuracao_bolao').select('*').limit(1).single().then(({data})=>data&&setCfg(data))},[]); async function save(){await supabase.from('configuracao_bolao').upsert(cfg); alert('Configuração salva')}; return <div className="panel"><h3>Configuração</h3><input value={cfg.nome} onChange={e=>setCfg({...cfg,nome:e.target.value})}/><input type="number" value={cfg.qtd_selecoes} onChange={e=>setCfg({...cfg,qtd_selecoes:+e.target.value})}/><input type="number" value={cfg.qtd_grupos} onChange={e=>setCfg({...cfg,qtd_grupos:+e.target.value})}/><input type="datetime-local" value={(cfg.limite_palpite||'').slice(0,16)} onChange={e=>setCfg({...cfg,limite_palpite:e.target.value})}/><button onClick={save}>Salvar configuração</button></div> }
function AdminSelecoes(){ const [nome,setNome]=useState(''),[cod,setCod]=useState(''),[grupo,setGrupo]=useState('A'),[list,setList]=useState([]); const load=()=>supabase.from('selecoes').select('*').order('grupo').then(({data})=>setList(data||[])); useEffect(load,[]); async function add(){await supabase.from('selecoes').insert({nome,codigo_bandeira:cod,grupo}); setNome('');setCod('');load()} return <div className="panel"><h3>Seleções</h3><input placeholder="Brasil" value={nome} onChange={e=>setNome(e.target.value)}/><input placeholder="br" value={cod} onChange={e=>setCod(e.target.value)}/><input placeholder="A" value={grupo} onChange={e=>setGrupo(e.target.value)}/><button onClick={add}><Plus size={16}/>Adicionar</button><p>{list.map(s=>`${s.grupo}-${s.nome}`).join(' | ')}</p></div> }
function AdminJogos(){ const [sels,setSels]=useState([]),[a,setA]=useState(''),[b,setB]=useState(''),[dt,setDt]=useState('2026-06-11T16:00'),[grupo,setGrupo]=useState('A'); useEffect(()=>{supabase.from('selecoes').select('*').then(({data})=>setSels(data||[]))},[]); async function add(){await supabase.from('jogos').insert({time_a_id:+a,time_b_id:+b,data_hora:dt,grupo}); alert('Jogo criado') } return <div className="panel"><h3>Jogos</h3><select onChange={e=>setA(e.target.value)}><option>Time A</option>{sels.map(s=><option value={s.id}>{s.nome}</option>)}</select><select onChange={e=>setB(e.target.value)}><option>Time B</option>{sels.map(s=><option value={s.id}>{s.nome}</option>)}</select><input value={grupo} onChange={e=>setGrupo(e.target.value)}/><input type="datetime-local" value={dt} onChange={e=>setDt(e.target.value)}/><button onClick={add}>Criar jogo</button><p>Resultados oficiais podem ser alterados diretamente na tabela jogos do Supabase ou em evolução da tela Admin.</p></div> }

createRoot(document.getElementById('root')).render(<App/>);
